pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=mergeit
    actions:
      merge:
        method: merge
